### ISSUE TITLE
Clean up loading states 

### ISSUE THREAD

**Issue by Schwartz10** [glifio/explorer#11]
just try searching for a CID and for an address... you'll see

**Comment by navFooh** [comment]
![image](https://user-images.githubusercontent.com/394452/154721707-825586ee-bd88-4513-a653-068d1c9e7b1e.png)

Loading states are now as follows. Also got rid of the animated fullscreen loader on the Message Overview table.

I much prefer to already see a general layout of the page and have the content loaded in.

The Message History table is now also always full width so that it doesn't jump too much when content is loaded in.

**Comment by navFooh** [comment]
And so I also added a header to the Transaction History, so it looks nice and consistent
