### ISSUE TITLE
Allow searching from the actor and message page

### ISSUE THREAD

**Issue by Schwartz10** [glifio/explorer#8]
Right now, once you make a search from the landing page, you're stuck there (unless you navigate by clicking links within those pages).

A user should be able to search again from all pages

I'd say just use your best judgement on the design here? But let me know if you want to spar on some ideas

**Comment by navFooh** [comment]
The search bar is now always present on top of the page.

One thing that bugs me a bit is the layout of the Glif icon here on the top-left. It doesn't align nicely with the rest of the content. Though the menu is now consistent with how it is on the homepage and we need the extra padding on the other pages, otherwise it looks too cramped.

What do you think?

![image](https://user-images.githubusercontent.com/394452/154723601-ad22d658-4dce-469e-9e57-1f349bdc98b3.png)
