### ISSUE TITLE
Improve look of error page 

### ISSUE THREAD

**Issue by Schwartz10** [glifio/explorer#9]
![image](https://user-images.githubusercontent.com/12353734/153235988-8dfab58f-793a-4561-9e05-7289c87e0d9b.png)

At the very least i feel like this could be centered?

**Comment by navFooh** [comment]
Error states now look as follows. We don't have the Back button anymore, though I wonder if we really need one, most people know how to go back in their browser. If we do want one, we might add it somewhere permanently instead of just on error?

![image](https://user-images.githubusercontent.com/394452/154722436-e5a48907-86b2-44fe-98e1-fd760a6f472c.png)

![image](https://user-images.githubusercontent.com/394452/154722657-b5bbc64e-12d3-44fc-b23e-fad3ae5554d4.png)
